language: python
matrix:
  include:
    - name: Code quality tests
      env: TOXENV=black,flake8,pylint,manifest
      python: 3.8
    - name: Unit tests with Python 3.8
      env: TOXENV=py38
      python: 3.8
    - name: Unit tests with Python 3.7
      env: TOXENV=py37
      python: 3.7
    - name: Unit tests with Python 3.6
      env: TOXENV=py36
      python: 3.6
    - name: Unit tests with PyPy 3
      env: TOXENV=pypy3
      python: pypy3
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$TRAVIS_BUILD_DIR/.tox"
install:
  - pip install tox
  - pip install -e .[test]
  - pip install pytest-cov codecov
script:
  - tox -e $TOXENV -- --cov-branch --cov-report=term-missing --cov=aiohttp_graphql
after_success:
  - codecov
