language: python
os:
- linux
python:
- 3.6
- 3.7
- 3.8-dev
- pypy3
cache:
  directories:
  - $HOME/.cache/pip
install:
- pip install -e .[test]
- pip install pytest-cov codecov
script:
- python -m pytest --cov-branch --cov=aiohttp_graphql --cov-report=term-missing
after_success:
- codecov
